---
title: SEDAS project Structure, Integration and Development
config:
    flowchart:
        curve: stepBefore
---
flowchart TD
    subgraph SEDAS documentation
        direction TB
            C --> D
    end

    subgraph SEDAS website
        direction TB
    end

    subgraph updater[SEDAS updater]
        u_A[Updater Main]
        u_A e6@--> u_B[Install]
        u_A e7@--> u_C[Uninstall]
        u_A e8@--> u_D[Fetching updates]
    end

    subgraph SEDAS manager
        m_A[SEDAS Core] -- Linked using Vite --- m_B[SEDAS Frontend]
        m_B e1@--> Virt
        m_B e2@--> Other
        m_B --> m_D[Controller GUI]

        subgraph Virt[Virtual Radar environment]
            direction LR
            virt_A[TWR mode] ~~~ virt_B[APP mode] ~~~ virt_C[ACC mode] ~~~ Dots1["..."]
        end

        subgraph Other

            direction TB

            subgraph Row1 [ ]
                direction LR

                subgraph Weather_Col [ ]
                    direction TB
                    mon_B[Weather UI]
                    mon_B e3@--> mon_E[Rainviewer API]
                    mon_B e4@--> mon_F[Custom sim weather]
                end

                subgraph Embed_Col [ ]
                    direction TB
                    mon_A[Embed] ~~~ Empty1["&nbsp;"]
                end

                subgraph Dep_Arr_Col [ ]
                    direction TB
                    mon_C[Departure/Arrivals] ~~~ Empty2["&nbsp;"]
                end

                subgraph Dots_Col [ ]
                    direction TB
                    Dots2["..."] ~~~ Empty3["&nbsp;"]
                end

                Embed_Col ~~~ Weather_Col ~~~ Dep_Arr_Col ~~~ Dots_Col
            end
        end

        subgraph Communication
            direction TB
            c_A[Communication Main]
            c_A --> c_B[Inter-Process-Communication]
            c_A e9@--> c_C[Module-Socket-Communication]
        end

        m_A[SEDAS Core] --- m_E[SEDAS Backend]
        m_E e5@--> m_F[OS Bridge]
        m_E ~~~ updater
        m_E --> u_A
        m_E ~~~ Communication
        m_E --> c_A
    end

    classDef animate stroke-dasharray: 9,5,stroke-dashoffset: 900,animation: dash 25s linear infinite;
    classDef invisible_container fill:none,stroke:none;
    classDef invisible_node fill:none,stroke:none,color:#fff,stroke-width:0px;
    classDef dotted fill:none,stroke:none,color:#fff,stroke-width:0px,font-size:40px,letter-spacing:10px;
    classDef todo stroke-width:2px,stroke-dasharray: 5 5;

    class e1,e2,e3,e4,e5,e6,e7,e8,e9 animate
    class Dots1,Dots2 dotted
    class Row1,Weather_Col,Embed_Col,Dep_Arr_Col,Dots_Col invisible_container
    class Empty1,Empty2,Empty3 invisible_node
    class mon_C,virt_A,virt_B todo