---
title: SEDAS project Structure, Integration and Development
---
flowchart TD

    main_A[Project Development Framework]
    main_A --> web
    main_A --> docs
    main_A -- Linked using representative container not to break **diagram structure** --> sedas_small_container
    main_A --> sedas_dev_tools

    subgraph AI_backend[ ]
        direction TB
        back_A[SEDAS AI backend]
        back_A --> whi_A
        back_A e25@--> back_B[AI backend handling]
    end

    subgraph ATC_whisper[ ]
        direction TB
        whi_A[ATC Whisper Project]
        whi_A e22@--> whi_B["Main (Training on **ATCOSIM** dataset)"]
        whi_A e21@--> whi_C["Model Playground"]
        whi_C --> whi_D["Whisper-ATC-czech-full **Weights**"]
        whi_C e20@--> whi_E[Other models]
    end

    subgraph MapBuilder[SEDAS MapBuilder]
        direction TB
    end

    subgraph updater[SEDAS updater]
        u_A[Updater Main]
        u_A e6@--> u_B[Install]
        u_A e7@--> u_C[Uninstall]
        u_A e8@--> u_D[Fetching updates]
    end

    subgraph sedas_small_container[ ]
        cont_header[SEDAS manager]
    end

    subgraph sedas_dev_tools[Dev tools and local testing]
        direction LR
        dev_A[Zed editor Debug setup] ~~~ dev_B[VSCode Debug setup]
    end

    subgraph sedas["<span style='font-size:30px; white-space:nowrap;'>SEDAS manager</span>"]
        m_A[SEDAS Core] -- Linked using Vite --- m_B[SEDAS Frontend]
        m_B --> Virt
        m_B --> Other
        m_B --> m_D[Controller GUI]

        subgraph Virt[Virtual Radar environment]
            direction LR
            virt_A[TWR mode] ~~~ virt_B[APP mode] ~~~ virt_C[ACC mode] ~~~ Dots1["..."]
        end

        subgraph Other

            direction TB

            subgraph Row1 [ ]
                direction LR

                subgraph Weather_Col [ ]
                    direction TB
                    mon_B[Weather UI]
                    mon_B e3@--> mon_E[Rainviewer API]
                    mon_B e4@--> mon_F[Custom sim weather]
                end

                subgraph Embed_Col [ ]
                    direction TB
                    mon_A[Embed] ~~~ Empty1["&nbsp;"]
                end

                subgraph Dep_Arr_Col [ ]
                    direction TB
                    mon_C[Departure/Arrivals] ~~~ Empty2["&nbsp;"]
                end

                subgraph Dots_Col [ ]
                    direction TB
                    Dots2["..."] ~~~ Empty3["&nbsp;"]
                end

                Embed_Col ~~~ Weather_Col ~~~ Dep_Arr_Col ~~~ Dots_Col
            end
        end

        subgraph Communication
            direction TB
            c_A[Communication Main]
            c_A --> c_B[Inter-Process-Communication]
            c_A e9@--> c_C[Module-Socket-Communication]
        end

        subgraph Module[Module Management]
            direction TB
            mod_A[Modules Main]
            mod_A --> AI_backend
            mod_A e16@--> mod_C[General Module Registry]
            mod_A e12@--> mod_B[General Module Management]
        end

        subgraph Plugin[Plugin Management]
            direction TB
            plu_A[Plugins Main]
            plu_A e19@--> MapBuilder
            plu_A e17@--> plu_B[General Plugin Registry]
            plu_A e18@--> plu_C[General Plugin Management]
        end

        subgraph Bridge[OS Bridge]
            direction TB
            bri_A[Bridge Main]
            bri_A e13@--> Linux
            bri_A e14@--> Windows
            bri_A e15@--> MacOS
        end

        m_A[SEDAS Core] --- m_E[SEDAS Backend]
        m_E e5@--> Bridge

        m_E e24@--> updater
        
        m_E --> Communication
    
        m_E e10@--> Module

        m_E --> Plugin
    end

    subgraph docs[SEDAS documentation]
        direction TB
        docs_A[Docs] e1@--> docs_B[User manual]
        docs_A e2@--> docs_C[ATC theory]
        docs_A e26@--> docs_D[Technical background]
        docs_A e27@--> docs_E[Tools]
        docs_E e28@--> docs_F[Automatic Translation]
    end

    subgraph web[SEDAS website]
        direction LR
        web_A[Website] ~~~ web_B[Codemap]
    end

    classDef animate stroke-dasharray: 9,5,stroke-dashoffset: 900,animation: dash 25s linear infinite;
    classDef invisible_container fill:none,stroke:none;
    classDef invisible_node fill:none,stroke:none,color:#fff,stroke-width:0px;
    classDef dotted fill:none,stroke:none,color:#fff,stroke-width:0px,font-size:40px,letter-spacing:10px;
    classDef todo stroke-width:2px,stroke-dasharray: 5 5;

    class e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e12,e13,e14,e15,e16,e17,e18,e19,e20,e21,e22,e24,e25,e26,e27,e28 animate
    class Dots1,Dots2 dotted
    class Row1,Weather_Col,Embed_Col,Dep_Arr_Col,Dots_Col invisible_container
    class Empty1,Empty2,Empty3,cont_header invisible_node
    class mon_C,virt_A,virt_B,dev_A,dev_B todo